import glob
import json
import os
import subprocess

def build_data():
	files = glob.glob( 'articles/*' )
	data = dict()
	data['comment'] = '*** THIS IS AN AUTOGENERATED FILE DO NOT MANUALLY EDIT ***'
	data['articles'] = []
	for f in files:
		# skip anything that has a dot or double underscore in the name
		# folders should not have a dot (it indicates an extension or hidden property)
		# I use __ to denote special things
		if '.' in f:
			continue
		if '__' in f:
			continue
		entry = dict(
			# change the slashes to forward slashed because the file
			# may be generated on any system but will be used in linux
			url = f.replace('\\','/'),
			title = f.replace('articles\\','').replace('-',' ').title()
		)
		try:
			jsonfile = open('%s/info.json' % f)
			try:
				entry.update( **json.loads( jsonfile.read() ) )
			except ValueError:
				print 'Error parsing json file: %s' % f
		except IOError:
			print 'Unable to open info.json: %s' % f
		finally:
			jsonfile.close()
		data['articles'].append( entry )
	with open( 'articles/list.json', 'w' ) as f:
		f.write( json.dumps( data ) )

if __name__ == '__main__':
	#build_data()
	env = os.environ.copy()
	env['HOME'] = env['USERPROFILE']
	#print '\n'.join( sorted(env.keys()) )
	#print env['HOME']
	#print subprocess.Popen(['git push origin gh-pages'], shell=True, env=env).communicate()
	print subprocess.Popen(['git','pull'], shell=True, env=env).communicate()
	print subprocess.Popen(['git','push','origin','gh-pages'], shell=True, env=env).communicate()
