import glob
import json

if __name__ == '__main__':
	files = glob.glob( 'articles/*' )
	data = dict()
	data['comment'] = '*** THIS IS AN AUTOGENERATED FILE DO NOT MANUALLY EDIT ***'
	data['articles'] = []
	for f in files:
		# skip anything that has a dot or double underscore in the name
		# folders should not have a dot (it indicates an extension or hidden property)
		# I use __ to denote special things
		if '.' in f:
			continue
		if '__' in f:
			continue
		data['articles'].append( dict(
			# change the slashes to forward slashed because the file
			# may be generated on any system but will be used in linux
			url = f.replace('\\','/'),
			title = f.replace('articles\\','').replace('-',' ').title()
		) )
	with open( 'articles/list.json', 'w' ) as f:
		f.write( json.dumps( data ) )

