import glob
import json
import os
import subprocess

def build_data():
	files = glob.glob( 'articles/*' )
	data = dict()
	data['comment'] = '*** THIS IS AN AUTOGENERATED FILE DO NOT MANUALLY EDIT ***'
	data['articles'] = []
	for f in files:
		# skip anything that has a dot or double underscore in the name
		# folders should not have a dot (it indicates an extension or hidden property)
		# I use __ to denote special things
		if '.' in f:
			continue
		if '__' in f:
			continue
		entry = dict(
			# change the slashes to forward slashed because the file
			# may be generated on any system but will be used in linux
			url = f.replace('\\','/'),
			title = f.replace('articles\\','').replace('-',' ').title()
		)
		try:
			jsonfile = open('%s/info.json' % f)
			try:
				entry.update( **json.loads( jsonfile.read() ) )
			except ValueError:
				print 'Error parsing json file: %s' % f
		except IOError:
			print 'Unable to open info.json: %s' % f
		finally:
			jsonfile.close()
		data['articles'].append( entry )
	with open( 'articles/list.json', 'w' ) as f:
		f.write( json.dumps( data ) )

if __name__ == '__main__':

	# THESE environment variables are for the _netrc if we want to use it
	# %HOME% will be set to 'C:\Users\"username"'.
	# Go that that folder (cd %HOME%) and make a file called '_netrc'
	# Note: Again, for Windows, you need a '_netrc' file, not a '.netrc' file.
	# Its content is quite standard (Replace the <examples> with your values):
	#	machine <hostname1>
	#	login <login1>
	#	password <password1>

	env = os.environ.copy()
	env['HOME'] = env['USERPROFILE']

	print 'Getting newest data from Git server.'
	subprocess.Popen(['git','pull'], shell=True, env=env).communicate()

	print 'Building site content.'
	build_data()

	print 'Committing updated site'
	subprocess.Popen(['git','commit','-am','build.py run and update of site'], shell=True, env=env).communicate()

	print 'Pushing data to server'
	subprocess.Popen(['git','push','origin','gh-pages'], shell=True, env=env).communicate()
